import type { DemoState, Proposal, User } from './types'

export const departments = ['Marketing', 'Operations', 'Partnerships', 'Technology', 'Finance', 'People Operations'] as const

export const seedUsers: User[] = [
  { id: 'u1', name: 'Mitch Gibbs', email: 'mitch.gibbs@pelicans.com', title: 'Demo administrator', roles: ['employee', 'admin'], departmentScopes: [], executiveScopes: [], active: true },
  { id: 'u2', name: 'Avery Chen', email: 'avery.chen@example.demo', title: 'Guest services coordinator', roles: ['employee'], departmentScopes: [], executiveScopes: [], active: true },
  { id: 'u3', name: 'Jordan Brooks', email: 'jordan.brooks@example.demo', title: 'Operations reviewer', roles: ['employee', 'approver'], departmentScopes: ['Operations'], executiveScopes: [], active: true },
  { id: 'u4', name: 'Morgan Reed', email: 'morgan.reed@example.demo', title: 'Strategy executive', roles: ['employee', 'executive'], departmentScopes: [], executiveScopes: ['Operations', 'Marketing'], active: true },
  { id: 'u5', name: 'Riley Patel', email: 'riley.patel@example.demo', title: 'Partnerships reviewer', roles: ['employee', 'approver'], departmentScopes: ['Partnerships'], executiveScopes: [], active: true },
  { id: 'u6', name: 'Taylor Monroe', email: 'taylor.monroe@example.demo', title: 'Revoked executive', roles: ['employee', 'executive'], departmentScopes: [], executiveScopes: ['Finance'], active: false },
]

export const seedProposals: Proposal[] = [
  { id: 'p1', title: 'Quiet arrival lane', summary: 'Pilot a low-stimulation venue entry lane with clearer pre-arrival guidance.', submitterId: 'u2', submitterDepartment: 'Operations', problem: 'Crowded entry can be difficult for guests with sensory needs.', solution: 'Designate one quieter lane and publish a simple arrival guide.', audience: 'Guests with sensory needs and accompanying families', primaryDepartment: 'Operations', supportingDepartments: ['Marketing'], values: ['People First', 'Community'], businessValue: ['Fan experience', 'Community engagement'], score: 84, scoreRationale: 'Strong fan and community benefit with a contained pilot.', feasibility: 'High', feasibilityRationale: 'Uses an existing gate and a limited-event trial.', status: 'Approved', risk: 'Lane demand and staffing assumptions need validation.', pilot: 'Test at two lower-attendance home events.', measures: ['Lane usage', 'Guest feedback', 'Average entry time'], version: 3, updatedAt: '2026-07-29' },
  { id: 'p2', title: 'Vendor credential fast track', summary: 'Pre-validate recurring vendor credentials before event week.', submitterId: 'u2', submitterDepartment: 'Operations', problem: 'Repeat vendors queue for the same manual validation.', solution: 'Create a recurring-vendor review and pre-approval checklist.', audience: 'Venue operations staff and recurring vendors', primaryDepartment: 'Operations', supportingDepartments: ['Technology'], values: ['Excellence', 'Teamwork'], businessValue: ['Operational improvement', 'Time savings'], score: 77, scoreRationale: 'Meaningful time savings; integration effort is not yet known.', feasibility: 'Moderate', feasibilityRationale: 'Process is pilotable but identity data handling needs review.', status: 'Department review', risk: 'Credential data and exception ownership require validation.', pilot: 'Run with five fictional vendor profiles in a tabletop exercise.', measures: ['Processing time', 'Exception rate', 'Staff hours'], version: 2, updatedAt: '2026-08-02' },
  { id: 'p3', title: 'Local artist concourse rotation', summary: 'Feature rotating community artwork in a defined concourse zone.', submitterId: 'u5', submitterDepartment: 'Partnerships', problem: 'Local creators have limited recurring visibility at events.', solution: 'Create a quarterly curated display with partner support.', audience: 'Local artists, guests, and community partners', primaryDepartment: 'Partnerships', supportingDepartments: ['Operations', 'Marketing'], values: ['Celebrate Individuality', 'Community'], businessValue: ['Community engagement', 'Partnership development', 'Fan experience'], score: 81, scoreRationale: 'Strong community and partnership value with modest revenue uncertainty.', feasibility: 'Moderate', feasibilityRationale: 'Requires curation, installation, rights, and sponsor validation.', status: 'Pilot', risk: 'Artwork rights, installation standards, and sponsor fit.', pilot: 'One 12-week installation in a single concourse zone.', measures: ['Artist participation', 'Guest sentiment', 'Partner interest'], version: 4, updatedAt: '2026-07-26' },
  { id: 'p4', title: 'Post-event shift pulse', summary: 'Collect a two-question mobile pulse after selected event shifts.', submitterId: 'u3', submitterDepartment: 'People Operations', problem: 'Frontline feedback arrives inconsistently and too late.', solution: 'Send a short opt-in pulse after selected shifts.', audience: 'Event-day employees and supervisors', primaryDepartment: 'People Operations', supportingDepartments: ['Technology', 'Operations'], values: ['People First', 'Integrity'], businessValue: ['Employee experience', 'Operational improvement'], score: 73, scoreRationale: 'Useful employee insight with privacy and response-rate uncertainty.', feasibility: 'Moderate', feasibilityRationale: 'Survey is simple; governance and follow-up ownership need definition.', status: 'Draft', risk: 'Anonymity expectations and survey fatigue.', pilot: 'Two questions after three selected events.', measures: ['Response rate', 'Actionable themes', 'Follow-up time'], version: 1, updatedAt: '2026-08-04' },
  { id: 'p5', title: 'Sponsor offer wallet', summary: 'Explore a mobile collection of sponsor offers for event attendees.', submitterId: 'u5', submitterDepartment: 'Partnerships', problem: 'Sponsor offers are distributed across disconnected channels.', solution: 'Prototype a single opt-in digital offer wallet.', audience: 'Opted-in attendees and participating partners', primaryDepartment: 'Partnerships', supportingDepartments: ['Technology', 'Marketing'], values: ['Excellence', 'Teamwork'], businessValue: ['Partnership development', 'Revenue generation', 'Fan experience'], score: 69, scoreRationale: 'Potential partnership value, reduced by technical and privacy unknowns.', feasibility: 'Low', feasibilityRationale: 'Identity, consent, redemption, and partner integrations are unresolved.', status: 'Rejected', risk: 'Consent, data sharing, fraud controls, and integration cost.', pilot: 'Clickable prototype with fictional offers only.', measures: ['Prototype completion', 'Partner feedback', 'Usability score'], version: 2, updatedAt: '2026-07-18' },
  { id: 'p6', title: 'Inventory exception digest', summary: 'Deliver a daily summary of high-priority inventory exceptions.', submitterId: 'u1', submitterDepartment: 'Finance', problem: 'Teams manually reconcile scattered exception reports.', solution: 'Consolidate defined exceptions into a daily digest.', audience: 'Finance and operations leads', primaryDepartment: 'Finance', supportingDepartments: ['Technology', 'Operations'], values: ['Excellence', 'Integrity'], businessValue: ['Time savings', 'Cost savings', 'Operational improvement'], score: 79, scoreRationale: 'Clear operational value; savings require baseline validation.', feasibility: 'High', feasibilityRationale: 'A read-only pilot can use exported fictional data.', status: 'Approved', risk: 'Source definitions and report ownership may differ by team.', pilot: 'Generate a two-week digest from sanitized sample data.', measures: ['Reconciliation time', 'Exceptions resolved', 'False positives'], version: 3, updatedAt: '2026-08-01' },
]

export const makeSeedState = (): DemoState => ({
  users: structuredClone(seedUsers),
  proposals: structuredClone(seedProposals),
  audit: [
    { id: 'a1', actor: 'Mitch Gibbs', action: 'Assigned executive scope', target: 'Morgan Reed: Operations, Marketing', at: '2026-07-24 09:40' },
    { id: 'a2', actor: 'Mitch Gibbs', action: 'Revoked demo access', target: 'Taylor Monroe', at: '2026-07-28 15:15' },
    { id: 'a3', actor: 'Jordan Brooks', action: 'Requested changes', target: 'Vendor credential fast track', at: '2026-08-02 11:22' },
  ],
  currentUserId: 'u2',
})
