import type { AuditEvent, DemoState, Department, Proposal, RoutingConfig, User } from './types'
import { buildApprovalStages } from './approval'

export const departments = ['Marketing', 'Operations', 'Partnerships', 'Technology', 'Finance', 'People Operations', 'Ticketing and Sales', 'Business Intelligence'] as const

export const routingConfig: RoutingConfig = {
  version: 'demo-routing-2026.08.11', confidenceThreshold: 55, ambiguityMargin: 10, collaboratorThreshold: 25, staleAfterDays: 180,
  humanReviewQueue: 'Human routing review', fallbackReviewerIds: ['u1'],
  weights: { remit: 20, responsibility: 20, skill: 15, subject: 30, dependency: 15 },
  departments: [
    { department: 'Marketing', remit: 'Campaigns, promotion, awareness, email, social media, advertising, content and guest communications.', subjects: ['campaign', 'promotion', 'awareness', 'email', 'social media', 'advertising', 'content', 'guest guide'], dependencySubjects: ['communication', 'launch message'], active: true },
    { department: 'Operations', remit: 'Game-day venue, security, staffing, entry, credentials and event logistics.', subjects: ['game day', 'venue', 'security', 'staffing', 'entry', 'gate', 'logistics', 'concourse', 'credential'], dependencySubjects: ['pilot operations', 'event execution'], active: true },
    { department: 'Partnerships', remit: 'Sponsors, brands, vendors, universities and outside organizations.', subjects: ['sponsor', 'partner', 'brand', 'vendor', 'university', 'outside organization', 'artist'], dependencySubjects: ['partner offer', 'sponsorship'], active: true },
    { department: 'Technology', remit: 'Websites, applications, systems, automation, integrations, identity and data platforms.', subjects: ['website', 'app', 'system', 'automation', 'mobile', 'digital', 'integration', 'identity', 'data'], dependencySubjects: ['technical integration', 'software'], active: true },
    { department: 'Finance', remit: 'Revenue, cost, budget, forecast, invoices and financial risk.', subjects: ['revenue', 'cost', 'budget', 'financial', 'savings', 'forecast', 'invoice'], dependencySubjects: ['business case', 'financial validation'], active: true },
    { department: 'People Operations', remit: 'Employee experience, recognition, morale, retention and workplace culture.', subjects: ['employee', 'staff morale', 'recognition', 'retention', 'workplace', 'shift feedback'], dependencySubjects: ['training', 'workforce'], active: true },
    { department: 'Ticketing and Sales', remit: 'Tickets, discounts, pricing, seats, inventory, admission and membership sales.', subjects: ['ticket', 'seat', 'admission', 'inventory', 'pricing', 'discount', 'member'], dependencySubjects: ['offer', 'sales'], active: true },
    { department: 'Business Intelligence', remit: 'Reporting, dashboards, analytics, metrics, forecasting and measurement.', subjects: ['report', 'dashboard', 'analytics', 'metric', 'forecast', 'measurement', 'digest'], dependencySubjects: ['measure', 'baseline'], active: true },
  ],
}

export const seedUsers: User[] = [
  { id: 'u1', name: 'Mitch Gibbs', email: 'mitch.gibbs@pelicans.com', title: 'Mock initial administrator', roles: ['employee', 'admin'], departmentScopes: [], executiveScopes: [], responsibilities: ['routing administration', 'human routing review'], skills: ['permission governance', 'routing configuration'], evidenceVerifiedAt: '2026-08-01', sensitivityAccess: ['standard', 'restricted', 'executive'], active: true },
  { id: 'u2', name: 'Avery Laurent', email: 'avery.laurent@example.demo', title: 'Experience designer', roles: ['employee'], departmentScopes: [], executiveScopes: [], responsibilities: ['guest experience design'], skills: ['accessible experiences'], evidenceVerifiedAt: '2026-07-15', sensitivityAccess: ['standard'], active: true },
  { id: 'u3', name: 'Rowan Price', email: 'rowan.price@example.demo', title: 'Venue operations reviewer', roles: ['employee', 'approver'], departmentScopes: ['Operations', 'Technology'], executiveScopes: [], responsibilities: ['venue entry', 'credential operations', 'technical integration'], skills: ['event logistics', 'security workflow', 'system implementation'], evidenceVerifiedAt: '2026-07-25', sensitivityAccess: ['standard', 'restricted'], active: true },
  { id: 'u4', name: 'Jordan Marchand', email: 'jordan.marchand@example.demo', title: 'Portfolio executive', roles: ['employee', 'executive'], departmentScopes: [], executiveScopes: ['Operations', 'Marketing'], responsibilities: ['portfolio oversight'], skills: ['pilot evaluation'], evidenceVerifiedAt: '2026-07-20', sensitivityAccess: ['standard', 'restricted'], active: true },
  { id: 'u5', name: 'Riley Patel', email: 'riley.patel@example.demo', title: 'Partnerships reviewer', roles: ['employee', 'approver'], departmentScopes: ['Partnerships', 'Marketing'], executiveScopes: [], responsibilities: ['sponsor activation', 'partner offer', 'campaign'], skills: ['partnership development', 'content review'], evidenceVerifiedAt: '2026-07-22', sensitivityAccess: ['standard'], active: true },
  { id: 'u6', name: 'Cameron Ellis', email: 'cameron.ellis@example.demo', title: 'Revoked executive', roles: ['employee', 'executive'], departmentScopes: [], executiveScopes: ['Finance'], responsibilities: ['financial portfolio review'], skills: ['forecasting'], evidenceVerifiedAt: '2026-02-01', sensitivityAccess: ['standard'], active: false },
]

const baseProposals: Proposal[] = [
  { id: 'p1', title: 'Quiet arrival lane', summary: 'Pilot a low-stimulation venue entry lane with clearer pre-arrival guidance.', submitterId: 'u2', submitterDepartment: 'Operations', problem: 'Crowded entry can be difficult for guests with sensory needs.', solution: 'Designate one quieter lane and publish a simple arrival guide.', audience: 'Guests with sensory needs and accompanying families', primaryDepartment: 'Operations', supportingDepartments: ['Marketing'], values: ['People First', 'Community'], businessValue: ['Fan experience', 'Community engagement'], score: 84, scoreRationale: 'Strong fan and community benefit with a contained pilot.', feasibility: 'High', feasibilityRationale: 'Uses an existing gate and a limited-event trial.', status: 'Approved', risk: 'Lane demand and staffing assumptions need validation.', pilot: 'Test at two lower-attendance home events.', measures: ['Lane usage', 'Guest feedback', 'Average entry time'], version: 3, updatedAt: '2026-07-29' },
  { id: 'p2', title: 'Vendor credential fast track', summary: 'Pre-validate recurring vendor credentials before event week.', submitterId: 'u2', submitterDepartment: 'Operations', problem: 'Repeat vendors queue for the same manual validation.', solution: 'Create a recurring-vendor review and pre-approval checklist.', audience: 'Venue operations staff and recurring vendors', primaryDepartment: 'Operations', supportingDepartments: ['Technology'], values: ['Excellence', 'Teamwork'], businessValue: ['Operational improvement', 'Time savings'], score: 77, scoreRationale: 'Meaningful time savings; integration effort is not yet known.', feasibility: 'Moderate', feasibilityRationale: 'Process is pilotable but identity data handling needs review.', status: 'Under review', risk: 'Credential data and exception ownership require validation.', pilot: 'Run with five fictional vendor profiles in a tabletop exercise.', measures: ['Processing time', 'Exception rate', 'Staff hours'], version: 2, updatedAt: '2026-08-02' },
  { id: 'p3', title: 'Local artist concourse rotation', summary: 'Feature rotating community artwork in a defined concourse zone.', submitterId: 'u5', submitterDepartment: 'Partnerships', problem: 'Local creators have limited recurring visibility at events.', solution: 'Create a quarterly curated display with partner support.', audience: 'Local artists, guests, and community partners', primaryDepartment: 'Partnerships', supportingDepartments: ['Operations', 'Marketing'], values: ['Celebrate Individuality', 'Community'], businessValue: ['Community engagement', 'Partnership development', 'Fan experience'], score: 81, scoreRationale: 'Strong community and partnership value with modest revenue uncertainty.', feasibility: 'Moderate', feasibilityRationale: 'Requires curation, installation, rights, and sponsor validation.', status: 'Pilot', risk: 'Artwork rights, installation standards, and sponsor fit.', pilot: 'One 12-week installation in a single concourse zone.', measures: ['Artist participation', 'Guest sentiment', 'Partner interest'], version: 4, updatedAt: '2026-07-26' },
  { id: 'p4', title: 'Post-event shift pulse', summary: 'Collect a two-question mobile pulse after selected event shifts.', submitterId: 'u3', submitterDepartment: 'People Operations', problem: 'Frontline feedback arrives inconsistently and too late.', solution: 'Send a short opt-in pulse after selected shifts.', audience: 'Event-day employees and supervisors', primaryDepartment: 'People Operations', supportingDepartments: ['Technology', 'Operations'], values: ['People First', 'Integrity'], businessValue: ['Employee experience', 'Operational improvement'], score: 73, scoreRationale: 'Useful employee insight with privacy and response-rate uncertainty.', feasibility: 'Moderate', feasibilityRationale: 'Survey is simple; governance and follow-up ownership need definition.', status: 'Human routing review', risk: 'Anonymity expectations and survey fatigue.', pilot: 'Two questions after three selected events.', measures: ['Response rate', 'Actionable themes', 'Follow-up time'], version: 1, updatedAt: '2026-08-04' },
  { id: 'p5', title: 'Sponsor offer wallet', summary: 'Explore a mobile collection of sponsor offers for event attendees.', submitterId: 'u5', submitterDepartment: 'Partnerships', problem: 'Sponsor offers are distributed across disconnected channels.', solution: 'Prototype a single opt-in digital offer wallet.', audience: 'Opted-in attendees and participating partners', primaryDepartment: 'Partnerships', supportingDepartments: ['Technology', 'Marketing'], values: ['Excellence', 'Teamwork'], businessValue: ['Partnership development', 'Revenue generation', 'Fan experience'], score: 69, scoreRationale: 'Potential partnership value, reduced by technical and privacy unknowns.', feasibility: 'Low', feasibilityRationale: 'Identity, consent, redemption, and partner integrations are unresolved.', status: 'Rejected', risk: 'Consent, data sharing, fraud controls, and integration cost.', pilot: 'Clickable prototype with fictional offers only.', measures: ['Prototype completion', 'Partner feedback', 'Usability score'], version: 2, updatedAt: '2026-07-18' },
  { id: 'p6', title: 'Inventory exception digest', summary: 'Deliver a daily summary of high-priority inventory exceptions.', submitterId: 'u1', submitterDepartment: 'Finance', problem: 'Teams manually reconcile scattered exception reports.', solution: 'Consolidate defined exceptions into a daily digest.', audience: 'Finance and operations leads', primaryDepartment: 'Finance', supportingDepartments: ['Technology', 'Operations'], values: ['Excellence', 'Integrity'], businessValue: ['Time savings', 'Cost savings', 'Operational improvement'], score: 79, scoreRationale: 'Clear operational value; savings require baseline validation.', feasibility: 'High', feasibilityRationale: 'A read-only pilot can use exported fictional data.', status: 'Approved', risk: 'Source definitions and report ownership may differ by team.', pilot: 'Generate a two-week digest from sanitized sample data.', measures: ['Reconciliation time', 'Exceptions resolved', 'False positives'], version: 3, updatedAt: '2026-08-01' },
]

const reviewerByDepartment: Partial<Record<Department, string>> = { Operations: 'u3', Technology: 'u3', Partnerships: 'u5', Marketing: 'u5' }

export const seedProposals = baseProposals.map((proposal): Proposal => ({
  ...proposal,
  responsibleReviewerId: proposal.status === 'Human routing review' ? null : reviewerByDepartment[proposal.primaryDepartment!] ?? null,
  reviewQueue: proposal.status === 'Human routing review' ? routingConfig.humanReviewQueue : null,
  routingConfidence: proposal.status === 'Human routing review' ? 42 : 78,
  routingEvidence: [{ id: `${proposal.id}-remit`, kind: 'remit', label: `${proposal.primaryDepartment} remit`, source: 'Administrator-maintained department catalog', verifiedAt: '2026-08-01', weight: 20 }],
  routingUncertainty: proposal.status === 'Human routing review' ? ['No permission-eligible People Operations reviewer is configured.'] : [],
  routingRuleVersion: routingConfig.version,
  sensitivity: proposal.id === 'p2' ? 'restricted' : 'standard',
  feedback: proposal.id === 'p2' ? [{ id: 'f1', authorId: 'u3', message: 'Please clarify who owns credential exceptions during the pilot.', visibleToSubmitter: true, createdAt: '2026-08-02T11:22:00Z' }] : [],
  nextAction: proposal.status === 'Human routing review' ? 'Authorized fallback reviewer assigns an accountable owner.' : proposal.status === 'Under review' ? 'Submitter responds to the visible reviewer question.' : 'Follow the current approval stage.',
}))

const audit: AuditEvent[] = [
  { id: 'a1', proposalId: 'p2', eventType: 'routing.assigned', timestamp: '2026-08-01T09:40:00Z', actorId: 'routing-service', actorLabel: 'Kickoff routing service', priorState: 'Pending routing', newState: 'Assigned', primaryBefore: null, primaryAfter: 'Operations', collaboratorsBefore: [], collaboratorsAfter: ['Technology'], reviewerBefore: null, reviewerAfter: 'u3', routingConfidence: 78, evidenceSummary: 'Operations remit, credential responsibility and security workflow skill.', ruleVersion: routingConfig.version, permissionDecision: 'Reviewer is active, scoped and allowed restricted proposals.', reason: 'Highest evidence-supported eligible candidate.' },
  { id: 'a2', eventType: 'access.revoked', timestamp: '2026-07-28T15:15:00Z', actorId: 'u1', actorLabel: 'Mitch Gibbs', priorState: 'Active', newState: 'Revoked', permissionDecision: 'Administrator action.', reason: 'Demonstrate immediate access loss.' },
  { id: 'a3', proposalId: 'p2', eventType: 'feedback.added', timestamp: '2026-08-02T11:22:00Z', actorId: 'u3', actorLabel: 'Rowan Price', priorState: 'Under review', newState: 'Under review', primaryBefore: 'Operations', primaryAfter: 'Operations', collaboratorsBefore: ['Technology'], collaboratorsAfter: ['Technology'], reviewerBefore: 'u3', reviewerAfter: 'u3', routingConfidence: 78, ruleVersion: routingConfig.version, permissionDecision: 'Visible to submitter and authorized reviewers.', reason: 'Requested pilot exception-owner clarification.' },
]

export const makeSeedState = (): DemoState => ({
  users: structuredClone(seedUsers),
  proposals: structuredClone(seedProposals.map((proposal) => ({ ...proposal, approvalStages: buildApprovalStages(proposal, seedUsers) }))),
  audit: structuredClone(audit),
  routingConfig: structuredClone(routingConfig),
  currentUserId: 'u2',
})
